#define YELLOW_BTN 17
#define RED_BTN 16 
#define GAME_RST_BTN 21
#define LED_R 20
#define LED_G 18
#define LED_B 19
#define RFID_RST 6
#define RFID_CS 1
#define RFID_SCK 2
#define RFID_MISO 0
#define RFID_MOSI 3
#define SPEAKER 22