name: CppCheck with MISRA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  cppcheck:
    name: CppCheck
    runs-on: ['ubuntu-latest']
    timeout-minutes: 2
    permissions:
        # only required for workflows in private repositories
        actions: read
        contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CppCheck
        shell: bash
        run: |
          sudo apt-get install cppcheck
          cppcheck --version
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lxml
      
      - name: Run CppCheck
        shell: bash
        run: $GITHUB_WORKSPACE/.github/scripts/checkmisra.sh